# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "90e3fc5e055c3421688ec0a18533881d"
name = "trust_badges_fo"
handle = "trust_badges_fo"
application_url = "https://arnold-biodiversity-exactly-reporter.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "theh2o2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://arnold-biodiversity-exactly-reporter.trycloudflare.com/auth/callback",
  "https://arnold-biodiversity-exactly-reporter.trycloudflare.com/auth/shopify/callback",
  "https://arnold-biodiversity-exactly-reporter.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
