# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d80d8f3b9e5ceabea945342274428aa0"
name = "trust-badge-app"
handle = "trust-badge-app-2"
application_url = "https://circuits-accommodations-fibre-dealtime.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "theh2o2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://circuits-accommodations-fibre-dealtime.trycloudflare.com/auth/callback",
  "https://circuits-accommodations-fibre-dealtime.trycloudflare.com/auth/shopify/callback",
  "https://circuits-accommodations-fibre-dealtime.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
